import Head from 'next/head'
import Products from "../components/Products/Products";
import React, { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import {setCustomerId, setToken, setUserId} from "../redux/features/auth/authSlice";
import { getUser } from "../redux/features/user/asyncUserActions";

function Home({ products, categories }) {
    const auth = useSelector(state => state.auth);
    const dispatch = useDispatch();

    useEffect(() => {
        const localLogin = async () => {
            const token = await localStorage.getItem('token');
            const userId = await localStorage.getItem('userId');
            const customerId = await localStorage.getItem('customerId');
            if (token) {
                dispatch(setToken(token));
                dispatch(setUserId(userId));
                dispatch(setCustomerId(customerId));
                dispatch(getUser({
                    token: token,
                    userId: userId,
                    customerId: customerId
                }))
            }
        }
        localLogin();
    }, [auth.userToken]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Products products={products}/>
      <p>lalasda</p>
    </>
  );

};

export default Home;